language: go

go:
        - 1.x

notifications:
  email: false

matrix:
  fast_finish: true

before_install:
        - mv ${TRAVIS_HOME}/gopath/src/github.com/ingvaar/grapi ${TRAVIS_HOME}/gopath/src/grapi
        - cd ${TRAVIS_HOME}/gopath/src/grapi
        
install:
        - go get

script:
        go build
