language: go

go:
        - 1.x

notifications:
  email: false

matrix:
  fast_finish: true

before_install:
        - go get github.com/go-sql-driver/mysql
        - go get github.com/mediocregopher/radix.v2/redis
        - go get github.com/gorilla/mux

script:
        go build
